
apiVersion: v1
kind: ConfigMap
metadata:
  name: concrnt-static
data:
  tos.txt: |-
    {{ .Values.legal.tos | nindent 4 }}
  register-template.json: |-
    {{ .Values.legal.registerTemplate | nindent 4 }}
  code-of-conduct.txt: |-
    {{ .Values.legal.codeOfConduct | nindent 4 }}
