{{- if .Values.activitypub2.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: activitypub2-config
data:
  config.yaml: |-
    server:
      port: 8008

    database:
      url: {{ .Values.activitypub2.databaseUrl | quote }}

    redis:
      url: {{ .Values.activitypub2.redisUrl | quote }}

    concrnt:
      domain: {{ .Values.concrnt2.fqdn }}
      privateKey: {{ .Values.activitypub2.privatekey | quote }}
{{- end }}
