apiVersion: v1
kind: ConfigMap
metadata:
  name: concrnt2-config
data:
  config.yaml: |-
    server:
      postgresDsn: {{ .Values.server.dsn2 }}
      gatewayAddr: http://concrnt2
      redisAddr: {{ .Values.server.redisAddr }}
      memcachedAddr: {{ .Values.server.memcachedAddr }}
      traceEndpoint: {{ .Values.observability.traceEndpoint }}
      enableTrace: {{ .Values.observability.enableTrace }}
      captchaSecret: {{ .Values.server.captchaSecret }}
      vapidPublicKey: {{ .Values.server.vapidPublicKey | quote }}
      vapidPrivateKey: {{ .Values.server.vapidPrivateKey | quote }}

    nodeInfo:
      fqdn: {{ .Values.concrnt.fqdn }}
      registration: {{ .Values.concrnt.registration }}
      privatekey: {{ .Values.concrnt.privatekey }}
      dimension: {{ .Values.concrnt.dimension }}

    profile:
      nickname: {{ .Values.profile.nickname }}
      description: {{ .Values.profile.description }}
      logo: {{ .Values.profile.logo }}
      wordmark: {{ .Values.profile.wordmark }}
      themeColor: {{ .Values.profile.themeColor | quote }}
      maintainerName: {{ .Values.profile.maintainerName }}
      maintainerEmail: {{ .Values.profile.maintainerEmail }}
      captchaSiteKey: {{ .Values.server.captchaSitekey }}

    services:
      - name: net.concrnt.legacy
        host: ccgateway
        port: 80
        paths:
          - /api/v1
          - /ap
          - .wellknown/webfinger
          - .wellknown/nodeinfo
          - .wellknown/host-meta
        preservePath: true
{{- if .Values.mediaserver.enabled }}
      - name: world.concrnt.mediaserver
        host: mediaserver
        port: 8000
        path: /storage
{{- end }}
{{- if .Values.hyperproxy.enabled }}
      - name: world.concrnt.hyperproxy.summary
        host: hyperproxy
        port: 8000
        path: /summary
        preservePath: true
      - name: world.concrnt.hyperproxy.image
        host: hyperproxy
        port: 8000
        path: /image
        preservePath: true
{{- end }}
{{- if .Values.search.enabled }}
      - name: net.concrnt.search
        host: cc-search
        port: 8000
        path: /search
{{- end }}
      - name: world.concrnt.web
        host: world-app
        port: 80
        path: /
        preservePath: true
