apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-relay-config
data:
  config.yaml: |-
    listen: ":8080"

    concrnt:
      domain: {{ .Values.concrnt.domain | quote }}
{{- if .Values.concrnt.ccid }}
      ccid: {{ .Values.concrnt.ccid | quote }}
{{- end }}
{{- if not .Values.useSecret }}
      privateKey: {{ .Values.concrnt.privatekey | quote }}
{{- end }}

    webhooks:
{{ toYaml .Values.webhooks | indent 6 }}
