apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ccgateway
  template:
    metadata:
      labels:
        name: ccgateway
    spec:
      containers:
      - name: ccgateway
        image: {{ .Values.concrnt.gatewayimage }}
        ports:
          - name: web
            containerPort: 8080
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3
        volumeMounts:
          - name: concrnt-config
            mountPath: /etc/concrnt/config
            readOnly: true
          - name: concrnt-static
            mountPath: /etc/concrnt/static
            readOnly: true
      volumes:
        - name: concrnt-config
          configMap:
            name: concrnt-config
        - name: concrnt-static
          configMap:
            name: concrnt-static

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccapi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ccapi
  template:
    metadata:
      labels:
        name: ccapi
    spec:
      containers:
      - name: ccapi
        image: {{ .Values.concrnt.appimage }}
        ports:
          - name: web
            containerPort: 8000
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3
        volumeMounts:
          - name: concrnt-config
            mountPath: /etc/concrnt/config
          - name: repository
            mountPath: /var/lib/concrnt
      volumes:
        - name: concrnt-config
          configMap:
            name: concrnt-config
        - name: repository
          persistentVolumeClaim:
            claimName: concrnt-repository



---

{{- if .Values.activitypub.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccactivitypub
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ccactivitypub
  template:
    metadata:
      labels:
        name: ccactivitypub
    spec:
      containers:
      - name: ccactivitypub
        image: {{ .Values.activitypub.image }}
        ports:
          - name: web
            containerPort: 8000
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3
        volumeMounts:
          - name: activitypub-config
            mountPath: /etc/concrnt/config
      volumes:
        - name: activitypub-config
          configMap:
            name: activitypub-config
{{- end }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccwebui
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ccwebui
  template:
    metadata:
      labels:
        name: ccwebui
    spec:
      containers:
      - name: ccwebui
        image: {{ .Values.concrnt.webimage }}
        ports:
          - name: web
            containerPort: 80
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /web/index.html
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 3

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: concurrent-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      name: concurrent-redis
  template:
    metadata:
      labels:
        name: concurrent-redis
    spec:
      containers:
      - name: redis
        image: redis:7-bookworm
        ports:
          - name: redis
            containerPort: 6379
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: redis-data
            mountPath: /data
{{- if .Values.observability.enabled }}
      - name: redis-exporter
        image: oliver006/redis_exporter:v1.6.0-alpine
        imagePullPolicy: IfNotPresent
        ports:
          - name: redis-exporter
            containerPort: 9121
        args:
          - "--redis.addr=redis://localhost:6379"
{{- end }}
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: concurrent-memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      name: concurrent-memcached
  template:
    metadata:
      labels:
        name: concurrent-memcached
    spec:
      containers:
      - name: memcached
        image: memcached:1.6-bookworm
        ports:
          - name: memcached
            containerPort: 11211
        imagePullPolicy: IfNotPresent
{{- if .Values.observability.enabled }}
      - name: memcached-exporter
        image: prom/memcached-exporter:v0.6.0
        imagePullPolicy: IfNotPresent
        ports:
          - name: memcached-expr
            containerPort: 9150
        args:
          - '--memcached.address=localhost:11211'
{{- end }}

---

{{- if .Values.monitoring.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      name: grafana-agent
  template:
    metadata:
      labels:
        name: grafana-agent
    spec:
      containers:
      - name: agent
        image: grafana/agent
        ports:
          - containerPort: 4318
        imagePullPolicy: Always
        volumeMounts:
          - mountPath: /etc/agent/agent.yaml
            name: observability-config
            subPath: agent.yaml

      - name: postgres-exporter
        image: quay.io/prometheuscommunity/postgres-exporter
        imagePullPolicy: IfNotPresent
        env:
          - name: DATA_SOURCE_NAME
            value: "postgresql://postgres:postgres@db:5432/postgres?sslmode=disable"

      - name: redis-exporter
        image: oliver006/redis_exporter:v1.6.0-alpine
        imagePullPolicy: IfNotPresent
        args:
          - "--redis.addr=redis://redis:6379"

      - name: memcached-exporter
        image: prom/memcached-exporter:v0.6.0
        imagePullPolicy: IfNotPresent
        args:
          - '--memcached.address=memcached:11211'

      volumes:
        - name: observability-config
          configMap:
            name: observability-config
            items:
            - key: agent.yaml
              path: agent.yaml
              mode: 0644
{{- end }}

---
{{ if .Values.mediaserver.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mediaserver
  template:
    metadata:
      labels:
        name: mediaserver
    spec:
      containers:
      - name: mediaserver
        image: {{ .Values.mediaserver.image }}
        ports:
          - name: web
            containerPort: 8000
        imagePullPolicy: IfNotPresent
        env:
          - name: bucketName
            value: {{ .Values.mediaserver.bucketName | quote }}
          - name: endpointUrl
            value: {{ .Values.mediaserver.endpointUrl | quote }}
          - name: accessKeyId
            value: {{ .Values.mediaserver.accessKeyId | quote }}
          - name: accessKeySecret
            value: {{ .Values.mediaserver.accessKeySecret | quote }}
          - name: publicBaseUrl
            value: {{ .Values.mediaserver.publicBaseUrl | quote }}
          - name: db_dsn
            value: {{ .Values.server.dsn | quote }}
          - name: quota
            value: {{ .Values.mediaserver.quota | quote }}
          - name: region
            value: {{ .Values.mediaserver.region | quote }}
{{ end }}

---
{{ if .Values.hyperproxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hyperproxy
  template:
    metadata:
      labels:
        name: hyperproxy
    spec:
      containers:
        - name: hyperproxy
          image: {{ .Values.hyperproxy.image }}
          imagePullPolicy: Always
          ports:
            - name: web
              containerPort: 8000
          env:
            - name: PORT
              value: "8000"
            - name: MEMCACHED_HOST
              value: {{ .Values.server.memcachedAddr | quote }}
{{ end }}

