{{if .Values.observability.enabled}}

# ccapi
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: concrnt-api
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      name: ccapi
  podMetricsEndpoints:
    - port: web

---
# ccgateway
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: concrnt-gateway
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      name: ccgateway
  podMetricsEndpoints:
    - port: web

---
# hyperproxy
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: concrnt-hyperproxy
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      name: hyperproxy
  podMetricsEndpoints:
    - port: web

---
# postgres
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: concurrent-db
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      name: postgres
  podMetricsEndpoints:
    - port: postgres-expr

---
# redis
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: concurrent-redis
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      name: redis
  podMetricsEndpoints:
    - port: redis-exporter

---
# memcached
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: concrnt-memcached
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      name: concurrent-memcached
  podMetricsEndpoints:
    - port: memcached-expr

{{end}}
