apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-varlib
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.dbstorage }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: concrnt-repository
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.repositoryStorage }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.server.redisstorage }}
