apiVersion: v1
kind: Service
metadata:
  name: ccgateway
  labels:
    name: ccgateway
spec:
  ports:
  - port: 80
    targetPort: web
    protocol: TCP
  selector:
    name: ccgateway
  type: {{ .Values.concrnt.servicetype }}

---
apiVersion: v1
kind: Service
metadata:
  name: ccapi
  labels:
    name: ccapi
spec:
  ports:
  - port: 8000
    targetPort: web
    protocol: TCP
  selector:
    name: ccapi
  type: ClusterIP

---

{{- if .Values.activitypub.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ccactivitypub
  labels:
    name: ccactivitypub
spec:
  ports:
  - port: 8000
    targetPort: web
    protocol: TCP
  selector:
    name: ccactivitypub
  type: ClusterIP
{{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: ccwebui
  labels:
    name: ccwebui
spec:
  ports:
  - port: 80
    targetPort: web
    protocol: TCP
  selector:
    name: ccwebui
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: concurrent-db
spec:
  ports:
  - port: 5432
    targetPort: postgres
    protocol: TCP
  selector:
    name: concurrent-db
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: concurrent-redis
spec:
  ports:
  - port: 6379
    targetPort: redis
    protocol: TCP
  selector:
    name: concurrent-redis
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    name: concurrent-memcached
spec:
  ports:
  - port: 11211
    targetPort: memcached
    protocol: TCP
  selector:
    name: concurrent-memcached
  type: ClusterIP

---

{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: grafana-agent
  labels:
    name: grafana-agent
spec:
  ports:
  - port: 4318
    protocol: TCP
  selector:
    name: grafana-agent
  type: ClusterIP
{{- end }}

---

{{ if .Values.mediaserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: mediaserver
  labels:
    name: mediaserver
spec:
  ports:
  - port: 8000
    targetPort: web
    protocol: TCP
  selector:
    name: mediaserver
  type: ClusterIP
{{ end }}

---
{{- if .Values.hyperproxy.enabled }}
kind: Service
apiVersion: v1
metadata:
  name: hyperproxy
spec:
  selector:
    name: hyperproxy
  ports:
    - port: 8000
      targetPort: web
      protocol: TCP
  type: ClusterIP
{{- end }}

---
{{- if .Values.search.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: cc-search
spec:
  selector:
    name: cc-search
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
{{- end }}

---
{{- if .Values.meilisearch.enabled }}

apiVersion: v1
kind: Service
metadata:
  name: meilisearch
spec:
  selector:
    name: meilisearch
  ports:
    - protocol: TCP
      port: 7700
      targetPort: 7700
  type: ClusterIP
{{- end }}


