apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: concurrent-db
spec:
  replicas: 1
  serviceName: concurrent-db
  selector:
    matchLabels:
      name: concurrent-db
  template:
    metadata:
      labels:
        name: concurrent-db
    spec:
      containers:
        - name: posgresql
          image: postgres:16-bookworm
          ports:
            - name: postgres
              containerPort: 5432
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: concrnt
          volumeMounts:
            - name: postgres-varlib
              mountPath: {{ .Values.server.dbMountPath }}
{{- if .Values.observability.enabled }}
        - name: postgres-exporter
          image: quay.io/prometheuscommunity/postgres-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres-expr
              containerPort: 9187
          env:
            - name: DATA_SOURCE_NAME
              value: "postgresql://postgres:postgres@localhost:5432/postgres?sslmode=disable"
{{- end }}
      volumes:
        - name: postgres-varlib
          persistentVolumeClaim:
            claimName: postgres-varlib

---
{{- if .Values.meilisearch.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: meilisearch
spec:
  serviceName: meilisearch
  replicas: 1
  selector:
    matchLabels:
      name: meilisearch
  template:
    metadata:
      labels:
        name: meilisearch
    spec:
      containers:
      - name: meilisearch
        image: {{ .Values.meilisearch.image }}
        ports:
          - containerPort: 7700
        imagePullPolicy: Always
        env:
          - name: MEILI_MASTER_KEY
            value: {{ .Values.search.meilisearchKey }}
        volumeMounts:
          - name: meilisearch-data
            mountPath: /data.ms
  volumeClaimTemplates:
  - metadata:
      name: meilisearch-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.meilisearch.storage }}
{{- end}}
