server:
  dsn: "host=db user=postgres password=postgres dbname=concrnt port=5432 sslmode=disable"
  redisAddr: "redis:6379"
  memcachedAddr: "memcached:11211"
  captchaSitekey: "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
  captchaSecret: "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"
  vapidPublicKey: ""
  vapidPrivateKey: ""

observability:
  createPodMonitors: false
  enableTrace: false
  traceEndpoint: "alloy:4318"

concrnt:
  appimage: ghcr.io/concrnt/ccapi:v1.7.4
  gatewayimage: ghcr.io/concrnt/ccgateway:v1.7.4
  webimage: ghcr.io/concrnt/web-dashboard:v0.0.5

  servicetype: ClusterIP
  fqdn: example.tld
  registration: invite
  privatekey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  dimension: concrnt-mainnet

  useSecret: false
  configpaths: "" # "/etc/concrnt/config/config.yaml:/etc/concrnt/secret/config.yaml"

profile:
  nickname: concrnt-domain
  description: domain description
  logo: ""
  wordmark: ""
  themeColor: "#20193b"
  maintainerName: changeme
  maintainerEmail: changeme@example.com

search:
  enabled: false
  image: ghcr.io/concrnt/cc-search:v0.1.2
  useSecret: false
  meilisearchKey: "concrnt-meilisearch"
  meilisearchUrl: "http://meilisearch:7700"
  meilisearchIdx: "concrnt"

mediaserver:
  enabled: false
  useSecret: false
  image: ghcr.io/totegamma/cc-media-server:v0.5.0
  bucketName: YOUR_BUCKET_NAME
  endpointUrl: https://xxxxxx.r2.cloudflarestorage.com
  accessKeyId: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  accessKeySecret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  publicBaseUrl: https://pub-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.r2.dev/
  region: auto
  quota: "1000000000"

activitypub:
  enabled: false
  useSecret: false
  image: ghcr.io/concrnt/ccworld-ap-bridge:v0.6.1
  privatekey: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  configpaths: "" # "/etc/concrnt/config/config.yaml:/etc/concrnt/secret/config.yaml"

hyperproxy:
  enabled: true
  image: ghcr.io/concrnt/hyperproxy:v0.3.5

legal:
  tos: ""
  registerTemplate: |
    {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "title": "名前",
          "description": "ご連絡が必要になった場合に用いる宛名　ハンドルネーム推奨"
        },
        "email": {
          "type": "string",
          "title": "メールアドレス",
          "description": "最終的なご連絡先 確認メールなどシステムでの利用はありません。"
        },
        "social": {
          "type": "string",
          "title": "その他連絡先",
          "description": "TwitterやMisskeyやMastodonなど"
        },
        "consent": {
          "type": "boolean",
          "title": "利用規約・行動規範およびプライバシーポリシーに同意します",
          "default": null,
          "enum": [
            null,
            true
          ]
        }
      },
      "required": [
        "name",
        "email",
        "consent"
      ]
    }
  codeOfConduct: |
    1. サーバーは日本国内に設置されています。日本の法律に従ってください。
    2. 他者へのリスペクトを忘れないようにしましょう。
    3. ユーザー名・アイコン・ステータスメッセージなどは他者を不快にさせるようなものは控え、投稿も内容によっては公開範囲をコントロールしましょう。
    4. コミュニティタイムラインでは、そのコミュニティの趣旨をくみ取り、適切な投稿を心がけましょう。

postgres:
  enabled: true
  storage: "1Gi"
  mountPath: "/var/lib/postgresql/data"
  createExporter: false
  useSecret: false

redis:
  enabled: true
  storage: "1Gi"
  createExporter: false

memcached:
  enabled: true
  createExporter: false

meilisearch:
  enabled: false
  useSecret: false
  image: getmeili/meilisearch:prototype-japanese-13
  storage: "1Gi"

